name: Build Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Verify API routes
      run: |
        # Check that API files can be imported without errors
        for file in api/*.js; do
          echo "Checking $file..."
          node -e "import('$(pwd)/$file').catch(e => { console.error(e); process.exit(1); })"
        done

    - name: Build frontend
      run: npm run build